---
name: Run-Env
version: 0.01_02
author:
  - 'Jozef Kutej <jozef@kutej.net>'
abstract: running environment detection
license: perl
requires:
  Carp::Clan: 0
  File::Spec: 0
  List::MoreUtils: 0
build_requires:
  Test::More: 0
provides:
  Run::Env:
    file: lib/Run/Env.pm
    version: 0.01_02
generated_by: Module::Build version 0.26
